
name: Mirror repo to S3
on:
  push:
    branches:
      - main
jobs:
  s3Backup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ AKIAU5XGNFAPXWV3N2KH }}
          MIRROR_TARGET: ${{ testbucketajrac }}
          SECRET_ACCESS_KEY: ${{ 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 }}
        with:
          args: --overwrite --remove
