provider "aws" {
  profile = "default"
  shared_credentials_file = "credential"
  region  = "us-east-1"#
}

locals {
  current_directory = "echo $(pwd)"
}

resource "aws_s3_bucket" "tf_course" {

  bucket = "raghavrharma3183"
  acl    = "private"
}

resource "null_resource" "git_clone" {
    provisioner "local-exec" {
    command = "git clone https://github.com/ajiteshsharma90/RRR.git"
    interpreter = ["bash"]
  }
}
resource "aws_s3_bucket" "tf_course_1" {
  
  for_each = fileset("$current_directory", "*")
  bucket   = aws_s3_bucket.tf_course.id
  key      = each.value
  source   = "$current_directory\\${each.value}"
  etag     = filemd5("$current_directory\\${each.value}")
}
